language: generic

sudo: required
services:
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get -y install docker-ce pass
    - echo 'DOCKER_OPTS="--experimental"' | sudo tee /etc/default/docker
    - sudo service docker restart
    - docker build -t bdev/client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bdev/client-test npm test

after_success:
    - docker build -t bdev/multi-client ./client
    - docker build -t bdev/multi-nginx ./nginx
    - docker build -t bdev/multi-server ./server
    - docker build -t bdev/multi-worker ./worker
    # Login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push bdev/multi-client
    - docker push bdev/multi-nginx
    - docker push bdev/multi-server
    - docker push bdev/multi-worker